name: traisformer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - cudatoolkit=11.8
  - matplotlib
  - numpy
  - pandas
  - tqdm
  - tensorboard
